/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idServer.h"

bool_t
xdr_id_response (XDR *xdrs, id_response *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_string (xdrs, &objp->id_response_u.message, ~0))
			 return FALSE;
		break;
	case 1:
		 if (!xdr_long (xdrs, &objp->id_response_u.id))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
