/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idServer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
idserverprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		long getnuevoidpuertaent_1_arg;
		long getnuevoidpuertasal_1_arg;
		long getidpuertaent_1_arg;
		long getidpuertasal_1_arg;
		long devolverid_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GetNuevoIDPersona:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getnuevoidpersona_1_svc;
		break;

	case GetNuevoIDPuertaEnt:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getnuevoidpuertaent_1_svc;
		break;

	case GetNuevoIDPuertaSal:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getnuevoidpuertasal_1_svc;
		break;

	case GetNuevoIDShMem:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getnuevoidshmem_1_svc;
		break;

	case GetIDPuertaEnt:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getidpuertaent_1_svc;
		break;

	case GetIDPuertaSal:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) getidpuertasal_1_svc;
		break;

	case DevolverID:
		_xdr_argument = (xdrproc_t) xdr_long;
		_xdr_result = (xdrproc_t) xdr_id_response;
		local = (char *(*)(char *, struct svc_req *)) devolverid_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (IDSERVERPROG, IDSERVERVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, IDSERVERPROG, IDSERVERVERS, idserverprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (IDSERVERPROG, IDSERVERVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, IDSERVERPROG, IDSERVERVERS, idserverprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (IDSERVERPROG, IDSERVERVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
