/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "idServer.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

id_response *
getnuevoidpersona_1(void *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetNuevoIDPersona,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
getnuevoidpuertaent_1(long *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetNuevoIDPuertaEnt,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
getnuevoidpuertasal_1(long *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetNuevoIDPuertaSal,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
getnuevoidshmem_1(void *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetNuevoIDShMem,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
getidpuertaent_1(long *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetIDPuertaEnt,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
getidpuertasal_1(long *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GetIDPuertaSal,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

id_response *
devolverid_1(long *argp, CLIENT *clnt)
{
	static id_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DevolverID,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_id_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
