/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDSERVER_H_RPCGEN
#define _IDSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct id_response {
	int error;
	union {
		char *message;
		long id;
	} id_response_u;
};
typedef struct id_response id_response;

#define IDSERVERPROG 0x20000001
#define IDSERVERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GetNuevoIDPersona 1
extern  id_response * getnuevoidpersona_1(void *, CLIENT *);
extern  id_response * getnuevoidpersona_1_svc(void *, struct svc_req *);
#define GetNuevoIDPuertaEnt 2
extern  id_response * getnuevoidpuertaent_1(long *, CLIENT *);
extern  id_response * getnuevoidpuertaent_1_svc(long *, struct svc_req *);
#define GetNuevoIDPuertaSal 3
extern  id_response * getnuevoidpuertasal_1(long *, CLIENT *);
extern  id_response * getnuevoidpuertasal_1_svc(long *, struct svc_req *);
#define GetNuevoIDShMem 4
extern  id_response * getnuevoidshmem_1(void *, CLIENT *);
extern  id_response * getnuevoidshmem_1_svc(void *, struct svc_req *);
#define GetIDPuertaEnt 5
extern  id_response * getidpuertaent_1(long *, CLIENT *);
extern  id_response * getidpuertaent_1_svc(long *, struct svc_req *);
#define GetIDPuertaSal 6
extern  id_response * getidpuertasal_1(long *, CLIENT *);
extern  id_response * getidpuertasal_1_svc(long *, struct svc_req *);
#define DevolverID 7
extern  id_response * devolverid_1(long *, CLIENT *);
extern  id_response * devolverid_1_svc(long *, struct svc_req *);
extern int idserverprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GetNuevoIDPersona 1
extern  id_response * getnuevoidpersona_1();
extern  id_response * getnuevoidpersona_1_svc();
#define GetNuevoIDPuertaEnt 2
extern  id_response * getnuevoidpuertaent_1();
extern  id_response * getnuevoidpuertaent_1_svc();
#define GetNuevoIDPuertaSal 3
extern  id_response * getnuevoidpuertasal_1();
extern  id_response * getnuevoidpuertasal_1_svc();
#define GetNuevoIDShMem 4
extern  id_response * getnuevoidshmem_1();
extern  id_response * getnuevoidshmem_1_svc();
#define GetIDPuertaEnt 5
extern  id_response * getidpuertaent_1();
extern  id_response * getidpuertaent_1_svc();
#define GetIDPuertaSal 6
extern  id_response * getidpuertasal_1();
extern  id_response * getidpuertasal_1_svc();
#define DevolverID 7
extern  id_response * devolverid_1();
extern  id_response * devolverid_1_svc();
extern int idserverprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_id_response (XDR *, id_response*);

#else /* K&R C */
extern bool_t xdr_id_response ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDSERVER_H_RPCGEN */
